In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("/content/titanic.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
y = df["Survived"]
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [6]:
X = df[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch"]]
X.head()

   Pclass   Age     Sex     Fare  SibSp  Parch
0       3  22.0    male   7.2500      1      0
1       1  38.0  female  71.2833      1      0
2       3  26.0  female   7.9250      0      0
3       1  35.0  female  53.1000      1      0
4       3  35.0    male   8.0500      0      0

In [7]:
X.isnull().sum()

Pclass      0
Age       177
Sex         0
Fare        0
SibSp       0
Parch       0
dtype: int64

In [11]:
X = df[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch"]].copy()

In [12]:
X["Age"] = X["Age"].fillna(X["Age"].median())
X["Sex"] = X["Sex"].map({"male": 0, "female": 1})

In [13]:
X["Age"].median()

28.0

In [14]:
X["Age"] = X["Age"].fillna(X["Age"].median())

In [16]:
X.isnull().sum()

Pclass    0
Age       0
Sex       0
Fare      0
SibSp     0
Parch     0
dtype: int64

In [17]:
X["Sex"] = X["Sex"].map({
    "male": 0,
    "female": 1
})

In [18]:
X.head()

   Pclass   Age  Sex     Fare  SibSp  Parch
0       3  22.0  NaN   7.2500      1      0
1       1  38.0  NaN  71.2833      1      0
2       3  26.0  NaN   7.9250      0      0
3       1  35.0  NaN  53.1000      1      0
4       3  35.0  NaN   8.0500      0      0

In [19]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Age     891 non-null    float64
 2   Sex     0 non-null      float64
 3   Fare    891 non-null    float64
 4   SibSp   891 non-null    int64
 5   Parch   891 non-null    int64
dtypes: float64(3), int64(3)
memory usage: 41.9 KB

In [20]:
X.isnull().sum()

Pclass      0
Age         0
Sex       891
Fare        0
SibSp       0
Parch       0
dtype: int64

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [22]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (712, 6)
X_test: (179, 6)
y_train: (712,)
y_test: (179,)

In [23]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count